//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RePackingCaden
{
    using System;
    using System.Collections.Generic;
    
    public partial class M_LOT_Cadena
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public M_LOT_Cadena()
        {
            this.M_CadenaID = new HashSet<M_CadenaID>();
        }
    
        public int ID { get; set; }
        public Nullable<int> LOTCode { get; set; }
        public int ModelID { get; set; }
        public string FullLOTCode { get; set; }
        public int LiterIndex { get; set; }
        public int BoxCapacity { get; set; }
        public int PalletCapacity { get; set; }
        public System.DateTime CreateDate { get; set; }
        public Nullable<bool> isActiv { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<M_CadenaID> M_CadenaID { get; set; }
        public virtual M_Models M_Models { get; set; }
    }
}
