//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RePackingCaden
{
    using System;
    using System.Collections.Generic;
    
    public partial class M_Packing_Cadena
    {
        public int ID { get; set; }
        public int TRIDShort { get; set; }
        public int PalletNum { get; set; }
        public int BoxNum { get; set; }
        public int UnitNum { get; set; }
        public int LineID { get; set; }
        public string Liter { get; set; }
        public int LOTID { get; set; }
        public int UserID { get; set; }
        public System.DateTime PackingDate { get; set; }
    }
}
