//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RePackingCaden
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class FASEntities : DbContext
    {
        public FASEntities()
            : base("name=FASEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<M_LOT_Cadena> M_LOT_Cadena { get; set; }
        public virtual DbSet<M_Packing_Cadena> M_Packing_Cadena { get; set; }
        public virtual DbSet<M_CadenaID> M_CadenaID { get; set; }
        public virtual DbSet<M_Models> M_Models { get; set; }
        public virtual DbSet<FAS_Users> FAS_Users { get; set; }
    }
}
